
  - description: ""
    label: "Module Blog"
    name: "module_blog"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/module_blog.tpl"
    content: "/content/module_blog.yaml"
    fields:
      - name: "blog_title_header"
        label: "Blog title Header"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_author_date"
        label: "Blog author-date"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
          options:
            0: "No"
            1: "Yes"
      - name: "blog_main_img"
        label: "Blog Main Img"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "text_contents"
        label: "Text Contents"
        description: ""
        datatype: "textarea"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "additional_contents"
        label: "Additional Contents"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "iframe_yt_vid"
        label: "Iframe yt vid"
        description: ""
        datatype: "textarea"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Module Category Badge Text"
    name: "module_category_badge_text"
    sort: 102
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "module_blog"
    content: "/content/module_category_badge_text.yaml"
    fields:
      - name: "badge_content"
        label: "Badge Content"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Module Blog Categories"
    name: "module_blog_categories"
    sort: 103
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "module_blog"
    content: "/content/module_blog_categories.yaml"
    fields:
      - name: "category_content"
        label: "Category Content"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "category_link"
        label: "Category Link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Module Blog Popular blogs"
    name: "module_blog_popular_blogs"
    sort: 104
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "module_blog"
    content: "/content/module_blog_popular_blogs.yaml"
    fields:
      - name: "img_thumbnail"
        label: "img-thumbnail"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_description"
        label: "Blog Description"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "popular_blog_link"
        label: "Popular Blog Link"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Module Blog Related Videos"
    name: "module_blog_related_videos"
    sort: 106
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "module_blog"
    content: "/content/module_blog_related_videos.yaml"
    fields:
      - name: "iframe_video"
        label: "Iframe Video"
        description: ""
        datatype: "textarea"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Module Blog Author Social Links"
    name: "module_blog_author_social_links"
    sort: 107
    listed: true
    hasRoute: false
    showAsTable: false
    parent: "module_blog"
    content: "/content/module_blog_author_social_links.yaml"
    fields:
      - name: "social_link"
        label: "Social Link"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "social_image"
        label: "social image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
